config:

  #Название региона с грузом
  boxRegionName: "boxes"

  #Название региона в который нужно относить груз
  skladRegionName: "sklad"

  #Название региона с зоной
  zonaRegionName: "zona"

  #Метод сдачи груза:
  #OLD - Сдача груза при помощи клика по блоку, который указан в skladMaterial
  #NEW - Груз сдается когда игрок заходит в регион склада (Как на кристаликсе)
  boxDeliveryMethod: "OLD"

  #Зарплата за доставку груза
  money: 10

  #Использовать альтернативную команду для выдачи денег/предметов (true - Да, false - Нет)
  useAlternativeCommand: false
  alternativeCommand: "give {player} diamond 1"

  #Название груза
  itemName: "&eСноп сена"
  itemLore:
    - "&8[&a&l!&8] &fОтнеси груз на склад"
    - "&8[&a&l!&8] &fи получи деньги."

  #Предмет который выдается игроку при взятии груза (по умолчанию сноп сена)
  itemMaterial: HAY_BLOCK

  #Блок который нужно грузить (по умолчанию сноп сена)
  boxMaterial: HAY_BLOCK

  #Блок, при нажатии на который груз пропадет (по умолчанию сундук)
  skladMaterial: CHEST

messages:
  noAdminPerm: "&cУ вас нет прав для выполнения этой команды"
  noPerm: "&e⛏ &fВы &cне можете &fработать грузчиком!"
  gamemode: "&e⛏ &fРаботать можно только в режиме выживания."
  dropItem: "&e⛏ &fГруз &cнельзя &fвыбросить!"
  zona: "&e⛏ &fТы ушел слишком &cдалеко &fот склада."
  heavybox: "&e⛏ &fГруз &aслишком тяжелый&f, вы &cне можете &fвзять больше одного."
  box: "&e⛏ &fОтнеси груз на &aсклад&f."
  noBox: "&e⛏ &fТебе &cнечего &fсдавать на склад."
  yesBox: "&e⛏ &fТы &aдоставил &fгруз на склад."
  pluginReloaded: "&aКонфиг плагина перезагружен"

  boxTitle: "&x&4&F&F&6&8&3Т&x&4&8&E&E&7&BЫ &x&3&9&D&D&6&CВ&x&3&2&D&5&6&4З&x&2&A&C&C&5&DЯ&x&2&3&C&4&5&5Л &x&3&5&D&8&6&7С&x&3&D&E&2&7&1Е&x&4&6&E&C&7&AН&x&4&F&F&6&8&3О"
  boxSubTitle: "&x&D&E&D&E&D&EН&x&D&9&D&9&D&9е&x&D&4&D&4&D&4с&x&C&F&C&F&C&Fи &x&C&4&C&4&C&4г&x&B&F&B&F&B&Fр&x&B&A&B&A&B&Aу&x&B&5&B&5&B&5з &x&B&6&B&6&B&6н&x&B&C&B&C&B&Cа &x&C&7&C&7&C&7с&x&C&D&C&D&C&Dк&x&D&3&D&3&D&3л&x&D&8&D&8&D&8а&x&D&E&D&E&D&Eд"

  skladTitle: "&x&9&7&F&5&B&4Д&x&8&C&E&B&A&9О&x&8&1&E&0&9&EС&x&7&6&D&6&9&4Т&x&6&B&C&B&8&9А&x&6&0&C&1&7&EВ&x&7&0&C&E&8&DЛ&x&8&0&D&C&9&DЕ&x&9&0&E&9&A&CН&x&A&0&F&6&B&BО"
  skladSubTitle: "&e+10$"